name: my_proj
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  shared:
      path: ../_shared

  provider: ^6.1.2
  intl: ^0.18.1

  font_awesome_flutter: ^10.4.0
  step_progress_indicator: ^1.0.2
  flutter_gif: ^0.0.4
  liquid_swipe: ^3.1.0
  flutter_animate: ^4.2.0+1
  image_gradient: ^0.0.2
  fluid_bottom_nav_bar: ^1.4.0
  motion_tab_bar: ^2.0.4
  search_choices: ^2.2.7
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.1.2
  http: ^1.1.0
  hover_menu: ^1.1.1
  carousel_slider: ^4.2.1



dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0
  intl: ^0.18.1
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/


  fonts:
    - family: FontMain
      fonts:
        - asset: assets/images/fonts/Joyboy.otf
    - family: FontMain1
      fonts:
        - asset: assets/images/fonts/Poppins-Regular.ttf
    - family: FontMain2
      fonts:
        - asset: assets/images/fonts/Metropolis-Regular.otf
    - family: FontMain3
      fonts:
        - asset: assets/images/fonts/Nunito-VariableFont_wght.ttf
    - family: OpenSans
      fonts:
        - asset: assets/images/fonts/OpenSans-Regular.ttf
        - asset: assets/images/fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/images/fonts/OpenSans-SemiBold.ttf
          weight: 600
    - family: Oswald
      fonts:
        - asset: assets/images/fonts/Oswald-Regular.ttf




